### PR TITLE
Add option to disable the toggle keybinding

### PR DESCRIPTION
**Pull request by Henkru**
Introduce a new configuration option `toggle_enabled` to enable/disable the the toggle keybinding. Default value is `true` (enabled), so no breaking changes.

### CODE REVIEW

**Comment by xeluxee** [comment]
Why not setting `toggle_style_key` to `<nop>`? See #89

**Comment by xeluxee** [comment]
Please take a look at #92, it'd be better to disable `toggle_style_key` by default, without introducing a new variable in configuration

**Comment by navarasu** [comment]
Appreciate @Henkru for your PR. As said @xeluxee, I think one more variable is not required. So closing this. Thank you for contribution.

**Comment by Henkru** [comment]
Agreed, makes more sense.

**Pull request closed without merging**
