### PR TITLE
fix: use new treesitter highlight groups

### PR DESCRIPTION
**Pull request by RubixDev**
In a recent commit nvim-treesitter removed support for the old `TS*` highlight groups that this theme depends on: https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f. This PR switches to the corresponding new highlight groups.

### CODE REVIEW

**Comment by navarasu** [comment]
From which neovim version this is getting changed. We need to support old neovim user also.

**Comment by RubixDev** [comment]
To my knowledge the new highlight groups already existed for some time and 0.8 just dropped support for the old ones, but I re-added the old groups again, just to be sure.

**Comment by fgazat** [comment]
Hello everyone. Just want to inform you.

I used `v0.7.0` and today I updated all plugins. It led to such warnings:
Screen Shot 2022-10-18 at 15 53 36

Then I updated neovim to `v0.8.0` and now everything is ok.

**Comment by RubixDev** [comment]
> I used `v0.7.0` and today I updated all plugins. It led to such warnings: [image](https://user-images.githubusercontent.com/43990410/196556546-f8b242b7-4145-4022-aa32-b5922bc337dc.png)

I can confirm, I did not test with 0.7 as I didn't expect it to break. Thanks for the info, I opened another PR to fix these warnings: #114.

**Comment by VPavliashvili** [comment]
Hello guys, I think its better if I report this here instead of raising new issue
After these changes(or changes in TreeSitter side not 100% sure) highlights overriding does not work properly. here is my configuration and it was working fine, but after PackerSync today it broke and I had to change fg color in this plugin's source code manually to have local variable's highlighting back to red.
```
-- this is my config of onedark.nvim
require('onedark').setup {
    style = 'deep',
    transparent = true,

    colors = {
        local_variable = "#ef5f6b",
    },

    highlights = {
        TSVariable = { fg = '$local_variable' },
    },
}

require('onedark').load()
```
I changed line 249 `fg = c.fg` to `fg = c.red` in `lua/onedark/highlights.lua` and this "fixed" my issue.

**Comment by navarasu** [comment]
I reverted all these changes and pushed it. But I see some color changes for cyan for symbols in ruby code. Checking it

**Comment by navarasu** [comment]
> Hello guys, I think its better if I report this here instead of raising new issue After these changes(or changes in TreeSitter side not 100% sure) highlights overriding does not work properly. here is my configuration and it was working fine, but after PackerSync today it broke and I had to change fg color in this plugin's source code manually to have local variable's highlighting back to red.
> 
> ```
> -- this is my config of onedark.nvim
> require('onedark').setup {
>     style = 'deep',
>     transparent = true,
> 
>     colors = {
>         local_variable = "#ef5f6b",
>     },
> 
>     highlights = {
>         TSVariable = { fg = '$local_variable' },
>     },
> }
> 
> require('onedark').load()
> ```
> 
> I changed line 249 `fg = c.fg` to `fg = c.red` in `lua/onedark/highlights.lua` and this "fixed" my issue.

Which version are you using?

**Comment by VPavliashvili** [comment]
@navarasu here is the output
```
nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by navarasu** [comment]
Added #114 Changes by @RubixDev . Pushed the changes

**Comment by navarasu** [comment]
> Hello guys, I think its better if I report this here instead of raising new issue After these changes(or changes in TreeSitter side not 100% sure) highlights overriding does not work properly. here is my configuration and it was working fine, but after PackerSync today it broke and I had to change fg color in this plugin's source code manually to have local variable's highlighting back to red.
> 
> ```
> -- this is my config of onedark.nvim
> require('onedark').setup {
>     style = 'deep',
>     transparent = true,
> 
>     colors = {
>         local_variable = "#ef5f6b",
>     },
> 
>     highlights = {
>         TSVariable = { fg = '$local_variable' },
>     },
> }
> 
> require('onedark').load()
> ```
> 
> I changed line 249 `fg = c.fg` to `fg = c.red` in `lua/onedark/highlights.lua` and this "fixed" my issue.

Please update latest https://github.com/nvim-treesitter/nvim-treesitter

**Comment by navarasu** [comment]
I think there is no use to support old [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) syntax for neovim 0.7.
As [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) mentioned, they support only version 0.8 or later

**Comment by VPavliashvili** [comment]
I have everything up to date but still does not seem to work. I tried settings `TSKeyword = '$green'` as its in README instructions but it changed string literals instead of keywords, highlights overriding seems to be broken

**Comment by RubixDev** [comment]
To override the treesitter groups one has to specify the new group names, as the old ones aren't used by nvim anymore. Try changing it to `["@keyword"] = '$green'`

**Comment by VPavliashvili** [comment]
@RubixDev Changed my config according to your suggestion and it worked. Than you very much
```
    colors = {
        local_variable = "#ef5f6b",
    },

    highlights = {
        ["@variable"] = {fg = '$local_variable'},
    },

```
I think it would be better if we include this change into README too, I can do pull request if you would be okay abt that

**Comment by VPavliashvili** [comment]
[Pull request created](https://github.com/navarasu/onedark.nvim/pull/115)

**Pull request merged**
