### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jackm245**
Create an array and fix typo on line 95, and remove trailing whitespace in README.md

### CODE REVIEW

**Comment by xeluxee** [comment]
We should also update this line since light theme has been added recently

https://github.com/navarasu/onedark.nvim/blob/49d668d5d7482c8e05584478570b14e93e13631b/README.md?plain=1#L81

**Comment by xeluxee** [comment]
@navarasu we should add light theme screenshot in README

**Comment by jackm245** [comment]
> We should also update this line since light theme has been added recently
> 
> https://github.com/navarasu/onedark.nvim/blob/49d668d5d7482c8e05584478570b14e93e13631b/README.md?plain=1#L81

I have updated this line, but for obvious reasons, will not be able to add the light theme screenshot

**Comment by navarasu** [comment]
> @navarasu we should add light theme screenshot in README

Yes. I need to. I have few correction on light theme and also adding one more light variant. I will update screenshot along with that

**Pull request merged**
