### PR TITLE
Adding semantic token support

### LINKED ISSUE #140: Doesn't look very good on Rust with semantic tokens from NeoVim 0.9
1. Traits' color is "Identifier" and ends up not looking very good
image
2. enum members, and attribute helpers, uses the same color and look like a blob
image
Comparison: With semantic tokens off:
image

### LINKED ISSUE #156: Support for Semantic Highlighting?
Now that Neovim v0.9 is available as a stable distribution, many users (myself included) found our syntax highlighting to be broken (see this [Reddit thread](https://www.reddit.com/r/neovim/comments/12gvms4/this_is_why_your_higlights_look_different_in_90/?utm_source=share&utm_medium=web2x&context=3) for an abridged discussion on the topic), this concern was partly reported in #140 as well.

I fixed the issues I was facing by clearing out the semantic highlighting & sticking with the Treesitter-based highlighting this plugin provides by adding the following lines of code to my `init.lua`:

```lua
for _, group in ipairs(vim.fn.getcompletion("@lsp", "highlight")) do
  vim.api.nvim_set_hl(0, group, {})
end
```
But it would be nice if this plugin could support Semantic Highlighting together with Treesitter-based highlighting as well. Lots of other colourscheme plugins already does it, examples are - [folke/tokyonight.nvim](https://github.com/folke/tokyonight.nvim) & [catpuccin/nvim](https://github.com/catppuccin/nvim).

### PR DESCRIPTION
**Pull request by chomosuke**
Fixes #156.
Fixes #140.

I wouldn't say I've made semantic tokens look good on every languages out there, but I do think this is good enough to be merged for now and be slowly improved later on. I do also think it is a significant improvement over how semantic tokens currently looks with nvim 0.9.

Here's how rust looks with treesitter only highlighting:
without semantic token

Here's how the same piece of rust looks with semantic token but before this PR, as you can see, it's quite unsightly:
before this PR

Here's how the same piece of rust looks with semantic token after this PR, notice how the doc test got syntax highlighting as it has been labeled by rust-analyzer:
with semantic token

BTW, I don't think parameters should be red but I can't think of any better color other than white so I'm opened to suggestions.

### CODE REVIEW

**Comment by jhossbach** [comment]
> BTW, I don't think parameters should be red but I can't think of any better color other than white so I'm opened to suggestions.
 
Maybe something like [jetbrain's one dark theme](https://github.com/one-dark/jetbrains-one-dark-theme)? 
[](https://raw.githubusercontent.com/one-dark/jetbrains-one-dark-theme/master/docs/screenshots/default.png)

**Comment by chomosuke** [comment]
@jhossbach not bad, I'll take that suggestion for now.

**Comment by jhossbach** [comment]
hey @navarasu, can we get this reviewed&pushed? I would love to use this colorscheme again!

**Comment by navarasu** [comment]
Can you please revert parameter colour change alone as it is not this PR scope? So that I can merge this code

**Comment by chomosuke** [comment]
@navarasu Done, shall I open param orange in another PR?

**Comment by chomosuke** [comment]
@DoumanAsh you can use `:Inspect` to check how are each char labeled. I highly suspect this is rust-analyzer or treesitter not updating or labeling the wrong thing.

**Comment by navarasu** [comment]
If we are changing the color, we need to check all language. I have handpicked all this color by checking look and feel on multiple languages. Raise it an issue, I will check it

**Pull request merged**
