### PR TITLE
refactor: refactor setup() function, handle old configuration and update highlights

### LINKED ISSUE #37: `setup()` refactoring
Hi
I think we should improve `setup` function to let users configure the entire plugin with it, using a config dictionary as argument
However, since the plugin should be configurable trough vimscript too, I think we could do keep a dictionary called `g:onedark_setup`, to be configured before calling the setup function.
All options would then be moved under this dictionary, except for `onedark_style`
Also custom highlights should be added as a setup option, solving issues #35, maybe #33, #23, maybe #17 and #12

@navarasu if you agree with these changes or you have some suggestion let me know, so I'll make a PR

### PR DESCRIPTION
**Pull request by xeluxee**
Fix #37

## Changes introduced with this PR:
- The configuration is kept in the global variable `vim.g.onedark_config`, to make it accessible from vimscript
- refactor `setup()`: now it accepts an argument, a dictionary containing options. **Note**: `setup()` only manages configuration, it doesn't load the colorscheme. To load the colorscheme you can `:colo onedark`

Example:
``` lua
require('onedark').setup {
  style = 'deep',
  toggle_style_key = '<leader>o',
  diagnostics = {
    darker = false,
    background = false,
  },
}
```
Of course it can be called without any argument: `require('onedark').setup()`, and the default configuration will be used

- `colors/onedark.vim` -> `colors/onedark.lua`
- `lua/onedark/config.lua` -> `lua/onedark/old_config.lua`, since this file is used to parse old configuration (if found it prints deprecation messages)
- highlights: deprecate `bold`, `underline`, `undercurl`, `italic` and `reverse` options in favor of `fmt`, a string that is ready to be used in highlight command. Example: `ErrorMsg = {fg = c.red, fmt = "bold,italic"}`. To see all the available attributes `:h attr-list` or [here](https://neovim.io/doc/user/syntax.html#attr-list) (they are the same for cterm and gui)
- highlights: trying to improve markdown highlights (#41), trough groups `TSTitle`, `TSURI`, `TSTextReference`
- highlights: update `nvim-cmp` highlights to support new kind icon colors
- highlights: improve `hop` highlights
- highlights: for C and C++ `TSOperator` is purple now, it looks better. I think we should consider colouring `TSOperator` for other languages too
- highlights: implemented `code_style` customization for various elements (comments, keywords, functions, strings and variables)
- colors: allow user to define custom colors or to overwrite existing ones.
- highlights: allow user to define custom highlights or to overwrite existing ones. Dollar prefix means a color from the colorscheme must be used. Example:
``` lua
require('onedark').setup {
  colors = {
    bright_orange = "#ff8800",    -- define a new color
    green = '#00ffaa',            -- redefine an existing color
  },
  highlights = {
    TSKeyword = {fg = '$green'},
    TSString = {fg = '$bright_orange', bg = '#00ff00', fmt = 'bold'},
    TSFunction = {fg = '#0000ff', sp = '$cyan', fmt = 'underline,italic'},
  }
}
```

## Usage
**NOTE**: all configurations must be done before setting the colorscheme 
#### Vimscript
``` vim
let g:onedark_config = {
  \ 'style': 'deep',
  \ 'toggle_style_key': '<leader>ts',
  \ 'ending_tildes': v:true,
  \ 'diagnostics': {
    \ 'darker': v:false,
    \ 'background': v:false,
  \ },
\ }
colorscheme onedark
```
**Note**: when using vimscript boolean values must be set with `v:true` and `v:false`, not `0` and `1`
#### Lua
``` lua
require('onedark').setup {
  style = 'warmer',
  toggle_style_key = '<leader>t',
  code_style = {
    comment = 'italic',
    keywords = 'bold,italic',
    strings = 'italic',
  },
  diagnostics = {
    darker = false,
    background = false,
  },
}
vim.api.nvim_command('colorscheme onedark')
```
#### Full config
``` lua
default_config = {
    -- Main options --
    style = 'dark',    -- choose between 'dark', 'darker', 'cool', 'deep', 'warm', 'warmer' and 'light'
    toggle_style_key = '<leader>ts',
    toggle_style_list = { 'dark', 'darker', 'cool', 'deep', 'warm', 'warmer', 'light' },
    transparent = false,     -- don't set background
    term_colors = true,      -- if true enable the terminal
    ending_tildes = false,    -- show the end-of-buffer tildes

    -- Changing Formats --
    code_style = {
        comments = 'italic',
        keywords = 'none',
        functions = 'none',
        strings = 'none',
        variables = 'none'
    },

    -- Custom Highlights --
    colors = {}, -- Override default colors
    highlights = {}, -- Override highlight groups

    -- Plugins Related --
    diagnostics = {
        darker = true, -- darker colors for diagnostic
        undercurl = true,   -- use undercurl for diagnostics
        background = true,    -- use background color for virtual text
    },
}
```

### CODE REVIEW

**Comment by xeluxee** [comment]
@navarasu now this PR is ready to be merged

**Comment by navarasu** [comment]
Thanks @xeluxee for your valuable. contribution. I will pull this code and will check in my local with all cases. Also will update the doc and merge tomorrow.

**Comment by xeluxee** [comment]
@navarasu I just pushed a bugfix commit, please give another pull before checking

**Comment by navarasu** [comment]
I pulled it in local and verified. Legacy vim styles work. But when i call 
```require('onedark').setup {
  style = 'warmer'}

**Comment by navarasu** [comment]
We need to call `M.colorscheme()` at last in setup. But I called `vim.api.nvim_command('colorscheme onedark')` to fix #28

**Comment by xeluxee** [comment]
> We need to call `M.colorscheme()` at last in setup. But I called `vim.api.nvim_command('colorscheme onedark')` to fix #28

@navarasu I don't agree, since `setup` function shouldn't load the colorscheme: other Neovim colorschemes uses `setup` only to configure theme options.
For example I don't always use onedark, but I want it to be configured in my `init.lua` trough `setup()`. So if later I want to switch to onedark I can simply `:colo onedark` without calling setup again with all the settings

**Comment by navarasu** [comment]
@xeluxee Yes, I agree. Maybe we can add a flag disable auto-setup

**Pull request merged**
