### PR TITLE
fix: make custom highlights update when colorscheme is set

### LINKED ISSUE #62: LspReference background colors do not toggle.
Hi, thanks for your great color schemes! 

I am tweaking some settings for the LSP reference highlights as I prefer a subtle background over an underline. My relevant setup is as follows:
```lua
require("onedark").setup({
    highlights = {
        LspReferenceText = { fmt = "none", bg = "$bg2" },
        LspReferenceWrite = { fmt = "none", bg = "$bg2" },
        LspReferenceRead = { fmt = "none", bg = "$bg2" },
    },
})
```
Now when I switch from dark to light (or vice versa) by either toggling or using `:set bg=light`, the LspReference* highlights keep the previous background, e.g. after switching from `warmer` to `light`: 
image

After sourcing the config manually, the correct backgrounds are set. Not a big issue to me, but I thought I'd let you know anyway.

### PR DESCRIPTION
**Pull request by xeluxee**
Fix #62 and fix a spell error from #63

### CODE REVIEW

**Comment by xeluxee** [comment]
@uhavin please try this PR and tell us if everything is fine

**Comment by navarasu** [comment]
@xeluxee If you are able to reproduce this issue  and this fix solves it, we can merge

**Comment by uhavin** [comment]
@xeluxee @navarasu I'll try it out in a moment.

**Comment by uhavin** [comment]
I can confirm this fixes the issue :tada:. (Sorry to keep you waiting).

**Comment by xeluxee** [comment]
Off topic, @navarasu do you plan to add light theme screenshot to readme?

**Comment by navarasu** [comment]
Yes I am planning to fix the issues in light theme color. I will add along with that

**Pull request merged**
